### ISSUE TITLE
doctype attribute in header is ignored

### ISSUE THREAD

**Issue by leif81** [asciidoctor/asciidoctor-maven-plugin#119]
I noticed that when I specify `:doctype: book` in the document header the generated HTML is still an article. Configuring the plugin with `<doctype>book</doctype>` seems to be the only way to change the doctype.

**Comment by mojavelinux** [comment]
Your observation is correct. This is because the doctype is being forcefully set via the API. We should probably only pass the doctype to the API if it is specified in the configuration.

See https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L156-L157
