### ISSUE TITLE
Empty output folders not purged

### ISSUE THREAD

**Issue by marceloverdijk** [asciidoctor/asciidoctor-maven-plugin#144]
When I have a setup like:

```
├──  src
│    ├──  index.adoc
│    ├──  _includes
│    │    ├──  some_include.adoc
```

The generated output will contain a empty `_include` folder.
I tried setting `preserveDirectories` to `false` without success.

Is there a way to purge empty folders?

**Comment by abelsromero** [comment]
Unfortunately there is no current way to do so right now. In the plugin, asciidoc files are converted one by one, and then additional resources are copied (folders included), it comes from issue #67.
I imagine we can add an option to remove empty folders once the process is complete, but this is not a simple task, because we should also take into consideration if we should enable recursive deleting.

Imho and to keep the plugin as simple as possible, I'd prefer to avoid adding extra options that are not directly related to AsciiDoctor itself. I can suggest as a workarround gmaven plugin. You can embed a simple groovy code to clean the targer folder at the end of the build, just check this link http://docs.codehaus.org/display/GMAVEN/Executing+Groovy+Code.

**Comment by abelsromero** [comment]
Hi @marceloverdijk, were you able to fix your issue with the suggested workarround?

**Comment by marceloverdijk** [comment]
No unfortunately not.

**Comment by abelsromero** [comment]
While I am open to reconsider this if someone else asks for it. It is also possible to set all non-necessary files in "hidden" directory prefixed by "_", none of the files, nor the directory itself will be copied to the target.
This I think is a cleaner solution.
