### ISSUE TITLE
Provide an option to enable Maven filtering

### ISSUE THREAD

**Issue by puce77** [asciidoctor/asciidoctor-maven-plugin#155]
Provide an option to enable Maven filtering.

Eg. built-in properties such as ${project.version} or custom properties are not replaced with the value of the property currently.

**Comment by abelsromero** [comment]
Theres a note about using pom's properties in the readme, However, it requires to set the properties you want to use, see if it helps:
https://github.com/asciidoctor/asciidoctor-maven-plugin#passing-pom-properties

Also, `project.version' is a special case and requires a small trick. After setting it in the pom, you must translate it in Asciidoc with this construct:
```
:revnumber: {docVersion}
```
You can find more information there's an old post in the forums with a bit more detail: http://discuss.asciidoctor.org/Maven-plugin-a-way-to-incorporate-a-maven-property-in-asciidoc-td992.html#a1000

I'm thinking also that if you want to appy 'full' maven resource filtering, it should be possible to apply the filters on the, copy the files to another folder and then render from it :/ Not nice and requires some extra work with phases since asciidoctor usually runs on `generate-resources`. 
Not perfect, but It keeps the plugin simple and focused on rendering Asciidoc.
