### ISSUE TITLE
sourceDir Absolute Vs Relative Paths

### ISSUE THREAD

**Issue by lgriffin** [asciidoctor/asciidoctor-maven-plugin#159]
Hi all,

I opened this originally on: https://github.com/asciidoctor/asciidoctor/issues/1307#issuecomment-97997866

I was told to file it here as it is more appropriate.

I have been looking at this for a few hours and came across a report on something similar https://github.com/asciidoctor/asciidoctor/issues/1175

My issue however is about the use of absolute Vs relative paths, this may be working as intended however I want to document it just in case.

The setup from the bug report above recommends sourceDir set as:

```xml
<sourceDir>${project.build.sourceDirectory}</sourceDir>
```

That allows me resolve down to the full path from my C drive right down to the /src/main/java folder.

When I include it in my asciidoc file as follows:
```
[source,java]
.Example.java
----
include::{sourceDir}/com/lgriffin/Example.java[]
----
```
And render it, I get the following appearing in a code box:

```
link:C:\Users\lgriffin\Documents\workspace\sample\src\main\java\com\lgriffin\Example.java[]
```
So it just provides the link to the absolute path. If I change my attribute for sourceDir to use the relative path which is as follows:

```xml
<sourceDir>../java</sourceDir>
```

It processes the code block as it should and renders the Example.java file (or any tags I specify) without any issues.

I'm wondering is this a bug?

**Comment by mojavelinux** [comment]
Leigh, we use almost this same scenario in the Maven examples (see https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoc-to-html-example). Could you try that and see if the include works (you should see a Java snippet in the html that appears in target/generated-docs).

There are three conditions under which an include is replaced with a link.

1. You are not using Asciidoctor 1.5.2 (see the fix made here for absolute Windows paths https://github.com/asciidoctor/asciidoctor/issues/1144)
2. The safe mode is secure or higher.
3. The target is a URL and the `allow-uri-read` attribute is not set

Can you verify you are using Asciidoctor 1.5.2? You can check by putting the `{asciidoctor-version}` attribute in your document somewhere. If you are using Asciidoctor < 1.5.2, then you need to set the `allow-uri-read` AsciiDoc attribute in the Maven plugin configuration.

If you are using Asciidoctor 1.5.2, are you setting the safe mode in your Maven configuration?

If you are using Asciidoctor 1.5.2, I can't see how the target is being detected as a URL since we now specifically don't match Windows paths (which look a bit URL-like). However, you could see if this line is being triggered by setting the `allow-uri-read` AsciiDoc attribute in the Maven plugin configuration and seeing if you get a different result.

As a side note, I recommend using all lowercase for attribute names like `sourcedir`.

**Comment by lgriffin** [comment]
Hey,

Thanks for the reply. It looks to be the version that was causing issue, I hadn't updated to 1.5.2 nor had I seen the prior issue with Windows Paths. I was basing a lot of my learning off of existing examples and documentation  which were obviously dated. Thanks for the clarification can switch to the latest versions and update my paths now!

Cheers,
Leigh

**Comment by mojavelinux** [comment]
Great news!

> I was basing a lot of my learning off of existing examples and documentation which were obviously dated. 

I took some time to update the documentation. It still needs work, but it's a start. See http://asciidoctor.org/docs/asciidoctor-maven-plugin/
