### ISSUE TITLE
Changing theme and custom CSS

### ISSUE THREAD

**Issue by Svish** [asciidoctor/asciidoctor-maven-plugin#173]
I'm using the maven plugin to convert my AsciiDoctor files into HTML5. 
1. How do I change from the default theme to one of the other alternatives listed at http://themes.asciidoctor.org/preview?
2. How can I add a custom CSS file for doing small tweaks? For example if I use a role on a block, which results in a CSS class being added, and want to give this CSS class some extra styling. I.e. I don't want to create a whole new theme or anything, just have a small file with some minor adjustments to the theme.

**Comment by Svish** [comment]
Re #2, I finally figured out I can use docinfo.html for this :+1:

Would still know if there's a way to do #1 though... without having to deal with the theme factory, ruby, sass, etc... Preferably I'd just like to add `<theme>foo</theme>`, or something along those lines.

**Comment by LightGuard** [comment]
Have you tried adding the theme as an option or attribute?

On Tuesday, November 3, 2015, Torleif Berger <notifications@github.com>
wrote:

> Re #2 <https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/2>, I
> finally figured out I can use docinfo.html for this [image: :+1:]
>
> Would still know if there's a way to do #1
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/1>
> though... without having to deal with the theme factory, ruby, sass, etc...
> Preferably I'd just like to add <theme>foo</theme>, or something along
> those lines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/173#issuecomment-153387895>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mojavelinux** [comment]
To use a separate stylesheet, you assign the `stylesheet` attribute to a relative or absolute path to an alternative stylesheet. Then, that stylesheet is used instead of the default stylesheet.

For details, see http://asciidoctor.org/docs/user-manual/#generate-an-html-document (though you need to assign the attribute in the Maven configuration instead of the CLI as shown in that section).

You could link directly to the stylesheet published on GitHub Pages (though I only recommend it for local testing).

```
-a stylesheet=http://themes.asciidoctor.org/stylesheets/colony.css
```

You don't have to use the stylesheet factory to make your own stylesheet. That's just a framework for making stylesheets. You are free to start from scratch if you want.

We don't currently bundle the other stylesheets produced by the stylesheet factory because they are intended only for demonstration and not rigorously maintained. We are considering publishing them, however. See https://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues/27

**Comment by Svish** [comment]
Yeah, I read about the `stylesheet` attribute, but the problem with that is that in my case I don't want to replace the default stylesheet (unless it was with another available complete theme), I want it in addition to the default stylesheet, for adjustments.

I've currently found I can use `docinfo.html` and add a `<style>` element there, and that seems to work fine, although I'd prefer to have it as a separate css file.

**Comment by mojavelinux** [comment]
Just create your own CSS file and use @import to bring in the default
stylesheet over your own rules.

You can extract the default stylesheet by running -a linkcss -a copycss
once.

This trick should definitely be documented.

**Comment by Svish** [comment]
Custom styling in general should be clearer documented I think. Kept reading about roles and how they could be used for that in the user manual, but not actually _how_ you could do this styling.

**Comment by mojavelinux** [comment]
Likely Asciidoctor HTML output needs to have a theming guide that looks a lot like the PDF theming guide.

Here's so more info about how to do all this: https://github.com/asciidoctor/asciidoctor.org/issues/422
