### ISSUE TITLE
Add failOnError configuration attribute

### ISSUE THREAD

**Issue by stuartwdouglas** [asciidoctor/asciidoctor-maven-plugin#178]
At the moment if there is an error in your docs you just get something like:

asciidoctor: ERROR: servlet-security.asciidoc: line 43: table missing leading separator, recovering automatically

This is very easy to miss, as it is just one line in the maven output. It would be much more useful IMHO if an error failed the build.

**Comment by mojavelinux** [comment]
I agree, but these warnings aren't actually visible to the API yet. That's what https://github.com/asciidoctor/asciidoctor/issues/44 is all about. It has to get fixed there first before we can do anything sensible in the build plugins. Otherwise, we have to parse STDOUT, a road we don't want to venture down.

**Comment by uniqueck** [comment]
I think we can close this issue.
