### ISSUE TITLE
sourceDocumentName with a document not in src/main/asciidoc

### ISSUE THREAD

**Issue by marcaurele** [asciidoctor/asciidoctor-maven-plugin#187]
Hi,

I have any issue with the change you did with the issue #58. If the path is relative to the expected source directory `src/main/asciidoc`, this directory **must** exist in order to process a file anywhere else in the project. My use case is a README.adoc in the root `${basedir}` I wish to process.

Setting the property to `<sourceDocumentName>../../../README.adoc</sourceDocumentName>` did not work because it fails while trying to copy the resources from `src/main/asciidoc` which does not exist.

Reading the comment of @mojavelinux on the issue #58 let me think that the plugin is not really design for such a use case. I just wanted to take up the subject to see if something could be done or not.

**Comment by abelsromero** [comment]
Good news is that if you want to render the README in the root ${basedir} you can with the following options:
```
    <sourceDirectory>${basedir}</sourceDirectory>
    <sourceDocumentName>README.adoc</sourceDocumentName>
```

Bad news is that that case is not 100% covered. You can do that, but all folders and non-Asciidoc files will be copied in the output directory. This incudes 'src/main/**', `src/test/**` and so on...

Ideally we want to be able to set filters to control what gets rendered/copied (see https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/174), but right now the option is to render the file, copy the folders and just use some other maven plugin to remove what you don't need.

**Comment by marcaurele** [comment]
Yep, I tested with scenario too but since it copies everything, it's not an option for me.

My use case can be one too if you have the README.adoc rendered by github and wish to generate the same file in your final archive. So for me it makes sense to find a solution for it, with the possibility to list multiple files (README.adoc, INSTALL.adoc...).

The first thing to fix is to not raise an error when trying to copy the assets if the `src/main/asciddoc` does not exist.

**Comment by abelsromero** [comment]
> The first thing to fix is to not raise an error when trying to copy the assets if the src/main/asciddoc does not exist.

Can you please post your configuration? I don't get that error and maybe you have found another related bug.

**Comment by marcaurele** [comment]
Ok, I won't be able to do it before Monday.

**Comment by abelsromero** [comment]
No worries :smile:  Post it when you can.

**Comment by marcaurele** [comment]
Originally it was splitted into 2 pom files (parent, child). I put everything in one, it should not make a difference.
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>sample.demo</groupId>
	<artifactId>something</artifactId>
	<packaging>pom</packaging>
	<version>1.0-SNAPSHOT</version>
	<name>Sample</name>

	<properties>
		<asciidoctorj-pdf.version>1.5.0-alpha.8</asciidoctorj-pdf.version>
		<asciidoctor.maven-plugin.version>1.5.2.1</asciidoctor.maven-plugin.version>
	</properties>

	<build>
		<plugins>
				<plugin>
					<groupId>org.asciidoctor</groupId>
					<artifactId>asciidoctor-maven-plugin</artifactId>
					<version>${asciidoctor.maven-plugin.version}</version>
					<dependencies>
						<dependency>
							<groupId>org.asciidoctor</groupId>
							<artifactId>asciidoctorj-pdf</artifactId>
							<version>${asciidoctorj-pdf.version}</version>
						</dependency>
					</dependencies>
					<configuration>
						<preserveDirectories>true</preserveDirectories>
						<sourceDocumentName>../../../README.adoc</sourceDocumentName>
						<headerFooter>true</headerFooter>
						<!-- Attributes common to all output formats -->
						<attributes>
							<docVersion>${project.version}</docVersion>
							<icons>font</icons>
							<toc />
							<sectanchors />
							<idprefix />
							<idseparator>-</idseparator>
						</attributes>
					</configuration>
					
					<!-- Double executions to generate HTML (fast) and PDF (slow) doc -->
					<executions>
						<execution>
							<id>generate-html-doc</id>
							<phase>generate-resources</phase>
							<goals>
								<goal>process-asciidoc</goal>
							</goals>
							<configuration>
								<backend>html</backend>
								<sourceHighlighter>coderay</sourceHighlighter>
								<attributes>
									<linkcss>false</linkcss>
								</attributes>
							</configuration>
						</execution>
						<execution>
							<id>generate-pdf-doc</id>
							<phase>generate-resources</phase>
							<goals>
								<goal>process-asciidoc</goal>
							</goals>
							<configuration>
								<backend>pdf</backend>
								<sourceHighlighter>coderay</sourceHighlighter>
								<attributes>
									<pagenums />
								</attributes>
							</configuration>
						</execution>
					</executions>
				</plugin>
		</plugins>
	</build>
	
</project>
```

**Comment by abelsromero** [comment]
I get the following error:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -18
        at java.lang.String.substring(String.java:1931)
        at org.asciidoctor.maven.AsciidoctorMojo.setDestinationPaths(AsciidoctorMojo.java:224)
        at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:187)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

Is that the error you mean? Or maybe is related to the parent/child configuration.

Accidentally, I got a 'FileNotFound' talking about 'src/main/asciddoc' but that was because I put the sourceDocumentName in the attributes section. Could be that the issue?

Btw, I'm working on an alternative to define what documents to render. Currently it supports multiple docs in the root path, you can even select multiple files from the root path and customize what additional files get copied.
Today I -wish- to push a preview. Since it involves a lot of changes maybe we schedule it for 1.6.0, but your feedback was very helpfull on this and I hope you can participate in the discussion
Thanks a lot!

**Comment by marcaurele** [comment]
This one is acutally another error.
I went back to the file I had and saw that I also played with the attribute <code>preserveDirectories</code> and turned it to <code>false</code>

With this configuration:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>sample.demo</groupId>
    <artifactId>something</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>Sample</name>

    <properties>
        <asciidoctorj-pdf.version>1.5.0-alpha.8</asciidoctorj-pdf.version>
        <asciidoctor.maven-plugin.version>1.5.2.1</asciidoctor.maven-plugin.version>
    </properties>

    <build>
        <plugins>
                <plugin>
                    <groupId>org.asciidoctor</groupId>
                    <artifactId>asciidoctor-maven-plugin</artifactId>
                    <version>${asciidoctor.maven-plugin.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctorj-pdf</artifactId>
                            <version>${asciidoctorj-pdf.version}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <preserveDirectories>false</preserveDirectories>
                        <sourceDocumentName>../../../README.adoc</sourceDocumentName>
                        <headerFooter>true</headerFooter>
                        <!-- Attributes common to all output formats -->
                        <attributes>
                            <docVersion>${project.version}</docVersion>
                            <icons>font</icons>
                            <toc />
                            <sectanchors />
                            <idprefix />
                            <idseparator>-</idseparator>
                        </attributes>
                    </configuration>

                    <!-- Double executions to generate HTML (fast) and PDF (slow) doc -->
                    <executions>
                        <execution>
                            <id>generate-html-doc</id>
                            <phase>generate-resources</phase>
                            <goals>
                                <goal>process-asciidoc</goal>
                            </goals>
                            <configuration>
                                <backend>html</backend>
                                <sourceHighlighter>coderay</sourceHighlighter>
                                <attributes>
                                    <linkcss>false</linkcss>
                                </attributes>
                            </configuration>
                        </execution>
                        <execution>
                            <id>generate-pdf-doc</id>
                            <phase>generate-resources</phase>
                            <goals>
                                <goal>process-asciidoc</goal>
                            </goals>
                            <configuration>
                                <backend>pdf</backend>
                                <sourceHighlighter>coderay</sourceHighlighter>
                                <attributes>
                                    <pagenums />
                                </attributes>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
        </plugins>
    </build>

</project>
```
I get this error:
```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-html-doc) on project bcv-net: Error copying resources: Source 'c:\workspaces\ADK-7.1\WEB_DEMO_ADK\src\main\asciidoc' does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-html-doc) on project bcv-net: Error copying resources
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error copying resources
        at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:195)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.io.FileNotFoundException: Source 'c:\workspaces\ADK-7.1\WEB_DEMO_ADK\src\main\asciidoc' does not exist
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368)
        at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:193)
        ... 21 more
```

I'll check the preview and let you know

**Comment by abelsromero** [comment]
Hi @marcaurele I have published a preview with the last PR that fixes this issue. I'd like to confirm with you that it helps before closing the issue.

The details of the preview are here:
https://bintray.com/abelsromero/maven/asciidoctor-maven-plugin/1.5.4-preview.2/

Source configuration work the same, the only change is that resources can be filtered like in the example.

```
<sourceDocumentName>./README.adoc</sourceDocumentName>
<resources>
    <resource>
        <directory>.</directory>
        <exclude>**/**</exclude> <!-- does not copy anything -->
    </resource>
</resources>
```

**Comment by mojavelinux** [comment]
I think we are using the term "filter" here to mean something different than what it means in the plugin. When you use the term filter here, I think you are talking about is selecting certain files and directories. I think what "filter" means in the maven-filtering plugin is whether variable references get replaced in the source as it gets copied. We should be careful not to mix up these meanings.

**Comment by mojavelinux** [comment]
Perhaps we should use the term "pattern filter" when we are talking about including or excluding files. I'm open to other ideas.

**Comment by mojavelinux** [comment]
I'm able to confirm that adding the following setting results in an error:

```
<filtering>true</filtering>
```

I wonder if internally we should be using the plain MavenResources instead of MavenResourcesFiltering.

I was also slightly confused about where `.` resolves. Does that refer to the value defined in the sourceDirectory option? Is it possible to specify paths outside of the sourceDirectory?

**Comment by abelsromero** [comment]
> I think we are using the term "filter" here to mean something different than what it means in the plugin. When you use the term filter here, I think you are talking about is selecting certain files and directories. I think what "filter" means in the maven-filtering plugin is whether variable references get replaced in the source as it gets copied. We should be careful not to mix up these meanings.

You are right, specially if the user guesses that we are using the 'maven-filtering' library under the hood. I will update the README, 'pattern filter' seems fine.
_But still I think that the use of word 'filter' in the plugin is not the best (sorry, I had to say it)._


> I'm able to confirm that adding the following setting results in an error:

True, I think that those options can be useful in the future, but untill they are documented we need to prevent their use in some way.

> I wonder if internally we should be using the plain MavenResources instead of MavenResourcesFiltering.

`maven-filtering` is the underlying library used by the maven-resource-plugin ([see](https://maven.apache.org/shared/maven-filtering/)), according to the documentation it was precisely created to separete file traversing logic so others could be used. Funny enough, the `Resource` type extends from `FileSet` which is exactly what I was aiming for, but all the directory/file traversing and pattern filtering is coupled with `Resource`. So, the options were to implement all from scratch, look for other libraries or use the `Resource` type.
I wanted to use something that maven users felt familiar with and avoid adding much code to the plugin, so I went for the third option. I am open to suggestions if someone knows other apis.

To fix the issue of the unused fields (e.g. filtering) I see three options:
1. Extend the Resource class and overwrite the setters of those field we won't people to use. In case of being invoked we can throw an exception and a message inviting users to post about what use cases they have, so we can implement something nice with it.
2. Leave as it is and document that those options should not be used.
4. Reset the fields during the maven execution and show a warning message. -> My least favourite, it's intrusive and not everyone pays attention to warning messages.


> I was also slightly confused about where . resolves. Does that refer to the value defined in the sourceDirectory option? Is it possible to specify paths outside of the sourceDirectory?

`.` resolves to the project folder, and YES you can do things like `..\.` to navigate to the directory outside of the project. I don't think it is a good practice, but in multi-module projects can get handy.

About the use of the sourceDirectoy, I though about it but discarded for it three reasons:
- Thinking ahead in future I'd like to add the option to select sources in a similar way. In that scenario  where one may have more than one sourceDirectory, it does not make sense to use them as root for resources. Note that the same feature can be achieved now using profiles, but it becomes extremely verbose and hard to mantain due to tones of duplicated settings.
- I think it removes flexibility in the sense that users may want to have different folders with different resources outside of the AsciiDoc documents structure. For instances several images with different quality/resolution.
- Again, trying to be as close as possible to the resource-maven-plugin. Note that you can use expresions like `${baseDir}` or `${sourceDirectory}` in the fields of a Resource, so messing with their value will be complicated and create many special cases that would need to be dealt with.

PS: I really try to keep my posts short :% sorry

**Comment by marcaurele** [comment]
@abelsromero I'm no longer working for the client for whom I was building the documentation with this plugin so I'm not able to test your change anymore. Thanks for the update and the work.

**Comment by abelsromero** [comment]
> @abelsromero I'm no longer working for the client for whom I was building the documentation with this plugin so I'm not able to test your change anymore. Thanks for the update and the work.

Thanks for letting me know, and thanks again for the feedback you provided to help with this improvement.

**Comment by abelsromero** [comment]
I've been testing and none of the options I proposed convice me now.
To begin with, maven does not use setters to initialize objects, so the only way to validate field is to do it directly in the Mojo or creating a subclass of Resource and adding some `validate fields`.

Looking into the issue further, now I see two options:
1. Validate the `filtering` field and throw an exception if it is set. `mergeId` is already set internally by the maven component and targetPath can be used. `targetPath` works nicely in that it resolves relative to the `outputDirectory` the user has defined, so I'd say we can expose it.
2. Add necessary dependencies for it to work, it's only 1 library.

I am not a fan of the 'maven hell' and I don't see a clear use for the filtering (property replacement) features, so I'd say, we can just validate the `filtering` option and throw an exception.

**Comment by abelsromero** [comment]
@marcaurele apologies for the spam, you can unsuscribe from the issue if you want.

**Comment by mojavelinux** [comment]
Thanks for your detailed responses @abelsromero!

> I think that the use of word 'filter' in the plugin is not the best (sorry, I had to say it).

100% agreed. In fact, I remember ranting out this almost a decade ago when I first started using Maven and was studying the documentation on the resources plugin. They definitely misused this word, esp given it was already used for filtering files in the Java API. (see http://docs.oracle.com/javase/1.5.0/docs/api/java/io/FilenameFilter.html).

> maven-filtering is the underlying library used by the maven-resource-plugin (see), according to the documentation it was precisely created to separete file traversing logic so others could be used. 

Got it. :+1: 

> I wanted to use something that maven users felt familiar with and avoid adding much code to the plugin, so I went for the third option. 

Then this is definitely the right decision.

> Reset the fields during the maven execution and show a warning message.

I think this is the right strategy, but I don't think the warning message is necessary. We don't have to say that we support all the options from maven-filtering, just that it works in the same familiar way.

I do think we can fix the filtering option so that it works. It just seems like we are missing a class or something.

> . resolves to the project folder, and YES you can do things like ..\. to navigate to the directory outside of the project.

Actually, you answered my question. I was wondering whether `.` was relative to the project or to the sourceDirectory. I understand it is relative to the project directory.

> Note that you can use expresions like ${baseDir} or ${sourceDirectory} in the fields of a Resource

:+1:

**Comment by mojavelinux** [comment]
>  Validate the filtering field and throw an exception if it is set. 

Can we just support it? I don't think it's wrong to allow it...in fact it might be desirable. We just need to figure out why it is failing. Maybe a dependency is missing?

**Comment by mojavelinux** [comment]
>  I don't see a clear use for the filtering (property replacement) features

Since it's not on by default, I think we should just allow it...but just not mention it in the docs (aka a power user feature).
