### ISSUE TITLE
Migrate plugin to Maven 3+ only

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#233]
Currently the plugin is using maven-plugin-api version 2.0 whereas the maven-project is 2.2.1 which is not consistent. Furthermore I think it's time to migrate to Maven 3+ only.
[Maven 2.2.1 has End Of Life](http://maven.apache.org/maven-2.x-eol.html) for more than two years in the meantime.
I thinks that should also in a major version upgrade to make clear that this is not compatible with Maven 2.X anymore ...

**Comment by khmarbaise** [comment]
This might be the right time to do that int 1.6.0 as well ?

**Comment by abelsromero** [comment]
Version 1.6.0 will be a major milestone with many non-back-compatible changes like moving to Java7 as minimum version and changes in AsciidoctorJ extension API.
Maybe I am being too prudent, but I'd keep 1.5.x versions compatible with maven 2.x.

wdyt?

**Comment by khmarbaise** [comment]
As I wrote...this is something for 1.6.0...

**Comment by abelsromero** [comment]
> As I wrote...this is something for 1.6.0...

Marked as 1.6.0 then!

To keep it, we can create a 1.6.0 branch or just keep the issue. What do you prefer?

**Comment by khmarbaise** [comment]
It would be useful having a branch for it so all changes can already been merged there...

**Comment by mojavelinux** [comment]
I agree to the branch. I think it should be the reverse though. I think we should have a branch for the 1.5.x series (named 1.5.x) and turn master's attention on 1.6.0.

**Comment by mojavelinux** [comment]
I suggest that because we tried it the other way around in AsciidoctorJ and ended up getting really confused. It's better that master permit any and all changes and that can only happen if it is forward looking.

**Comment by abelsromero** [comment]
> I suggest that because we tried it the other way around in AsciidoctorJ and ended up getting really confused. It's better that master permit any and all changes and that can only happen if it is forward looking.

If I understand that right, that means we cannot have a future branch, in cases like the ones that affect 'backward compatibility' we need to delay PR until master is ready.

**Comment by khmarbaise** [comment]
That only depends on how you merge the changes from the PR's and the changes from the master back to the future branch...

**Comment by mojavelinux** [comment]
I prefer master to the future branch. I don't like the idea of branches being ahead of master in the upstream (yes, in forks, of course). I think branches should be for older, stable release lines.

We tried having a future branch in AsciidoctorJ and it was quickly forgotten, only to lead to a massive divergence between two forward-looking branches. That's why I prefer master to mean "what's coming".

**Comment by mojavelinux** [comment]
I will mention that Asciidoctor Gradle plugin uses a development branch, which is ahead of master. However, I have yet to be convinced of the point of such a branch.

**Comment by abelsromero** [comment]
So, basically that means:

- current: branch named after version
- future: master for future releases. This means that some merge/cherry pick will be required from current
- past: old branches named after versions that can be deleted after some time

Last thing to clarify is what branch should be set as default in GitHub? Last released or current development?
I am more for the released version, that way people googling will see the documentation for the current version.

**Comment by mojavelinux** [comment]
Yes, that analysis is correct.

However, I think it's the other way around for cherry picks. Changes should almost always go into master first unless they are fixing something only relevant for a branch (perhaps because the code has diverged).

I think master should still be the default branch. However, we can have a comment at the top of the README that if you are working with an older release, you should navigate to that branch. We can provide links.

As always, I'm always open to reevaluating once we try it. We want to choose what feels right. But we don't always know what will feel right for us until we try. As Cornel West advises, "interrogate your assumptions."

**Comment by mojavelinux** [comment]
..in fact, that's the beauty of branches. It solves our "you are looking at the wrong documentation" problem. With a branch, we get that for free since the documentation will stay with the state of the branch.

**Comment by abelsromero** [comment]
I fear we aren't on the same page, If I understand your last comment right, this means that future changes need to be stalled untill master is ready.

Going with an example what I meant is the following:

Let's say we have release 1.5.4 and we are working on 1.5.5-SNAPSHOT, that means:

- _current_ will be branch 'asciidoctor-maven-plugin-1.5.5': PRs will be merged here by default.
- _future_ will be master: for instance, this could include a change that removes Java6 compatibility or any 1.6.0 scheduled stuff. Fixes and changes applied in 1.5.5 will need to be cherry picked to master periodically or when a version is released. At that point, a new branch should be forked from master to become _current_.
- _past_ will be old branches: in our current situation this means we need to create a 1.5.4 branch. In case of a hotfix we can always use one of those to apply a change and release.

After this example I think this is the same as AsciidoctorJ is douing but using master instead of a dedicated branch for 1.6.0.

**Comment by abelsromero** [comment]
Done https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/345
