### ISSUE TITLE
travis build does not configure the cache

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#246]
The cache usage should be configured in travis build to prevent downloading of deps in every build.
```
cache:
    directories:
    - $HOME/.m2
```

**Comment by mojavelinux** [comment]
Generally, we have not cached dependencies to ensure a clean room build. My
assumptions could be outdated, but in the past Maven could start relying on
a dependency it's already downloaded, but would fail if it was removed. If
you're confident this is an impossible scenario, then I'd be okay with
caching m2.

We could also flush m2 once a day or week.

**Comment by khmarbaise** [comment]
If a dependency is removed from the cache (I don't know by whome but this is an other story) it will downloaded...Furthermore you don't do `mvn install` (which you should never do)...you have a clean area...and yes it would be wise to flush the m2 folder once a day ? Or only in cases of problems https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches ? (manually)...

**Comment by abelsromero** [comment]
We did use cache at some time, but we stop using it and part of the configuration remained in the file, but I don't recall it was due to an issue.

> in the past Maven could start relying on
> a dependency it's already downloaded, but would fail if it was removed

If a liberary is removed maven will just download it again, the issue is if the pom or the jar becomes corrupt, in that case it will fail and it neves tries to download unless flushed. I quite confident about that, I work with many non-public libraries (for license issues) and messing this the local repo is a thing I suffer a lot (and yes, not everyone has an internal nexus).

My vote is to set the cache, if we detect issues we can clean it with the travis client or just disable it.

**Comment by khmarbaise** [comment]
So if this happens the question why a pom or jar file gets corrupted? There must be a reason for that? And if you don't use a repository manager you generally making a mistake in using Maven...If you have download problems etc. than this can cause problems with jar's or pom's...but this is something different. That's why it is fundamental to use a repository manager...not only for such things also for storing jar's which are not in Maven Central or other repositories (makes configuration more simpler and reliable) or other artifacts from other areas of a company etc. and of course for jar's with license issues...and to control the license and compliance in a better way etc. etc...improving build speed etc.

**Comment by abelsromero** [comment]
> So if this happens the question why a pom or jar file gets corrupted?

Corporate VPN & proxies mainly...random disk failure and pixies other times. It happens very rarely but when it does, unless you know the symptoms it can ruin a few hours of work.
In the case of travis/appveyor I don't think we need to worry, hence my proposal to enable cache.

> That's why it is fundamental to use a repository manager...

No need to tell me, but I am contractor and clients are clients...and sometimes you have to deal with some curious infrastructure.

**Comment by khmarbaise** [comment]
I'm a contractor too...sure I know...;-)

**Comment by mojavelinux** [comment]
In the past, my experience has been that Maven's cache can lead to the "works on my machine problem". Aside from the corrupt pom issue (often caused by proxies), Maven can collect jars in the cache that didn't come from the central repository (such as a local build or custom repository). Obviously, that's not a very likely scenario with this plugin since we only use central. It's more likely when you have a corporate environment and multiple non-public repositories. Long story short, Maven's cache can give a false positive of what is available in the remote repositories.

Since this is very unlikely to cause us a problem, I'm in favor of caching .m2 and flushing it manually if we have a problem (Travis offers a button to flush the cache).
