### ISSUE TITLE
codeMirror as sourceHighlighter ?

### ISSUE THREAD

**Issue by M3lkior** [asciidoctor/asciidoctor-maven-plugin#260]
Hi,

here is a way to support/use codeMirror in sourceHighlighter option ?

**Comment by abelsromero** [comment]
I guess you mean this https://codemirror.net/ is not supported in Asciidoctor. Keep in mind that Asciidoctor focuses on generating output, so I don't see how a life edition tool fits into this space. Even when I can see some sense in use cases like blogging.

Said that, and checking how CodeMirror works, I think that an extension could be possible. But deppending on the use case, it may require lots of options.

**Comment by mojavelinux** [comment]
CodeMirror is a popular source code highlighter (in addition to being an interactive editor). Asciidoctor does not currently support CodeMirror out of the box. What we're going to need to do is make the source highlighter integration an extension point. We simply cannot support all the source code highlighters in core because it's too much engineering effort. What we can do is provide a selection, then allow the community to maintain those additional integrations as separate projects.

Of course, you could managed to inject the CodeMirror scripts by using docinfo files, then perhaps use html-pipeline as the source highlighter, which just adds the language hint to the HTML.

**Comment by M3lkior** [comment]
I understand, thanks.  This gist lets me thinking that codeMirror is natively supported by asciidoctor : http://gist.asciidoctor.org/?github-asciidoctor%2Fdocgist%2F%2Fgists%2Fcodemirror.adoc#codemirror

CodeMirror have actually the best support for JSX language,

**Comment by mojavelinux** [comment]
@M3lkior Indeed, Neo (who maintains DocGist) integrated CodeMirror as an add-on. You can use the code as a reference for your own integration. Technically, there's nothing really that Asciidoctor core does to enable client-side source highlighters other than loading the script and running it.

See https://github.com/asciidoctor/docgist/blob/master/js/docgist.js

**Comment by abelsromero** [comment]
I understand the questions has been resolved.
