### ISSUE TITLE
Fail on warnings

### ISSUE THREAD

**Issue by Tillerino** [asciidoctor/asciidoctor-maven-plugin#261]
So basically, there are a ways to break your documentation without touching your asciidoc. The most prominent way would be to move an included source file. In this case, asciidoctor produces a warning, but since you didn't work on the documentation, you wouldn't look at the produced documentation or the output of asciitoctor, so it would go by unnoticed.

It would be great if your CI would be able to catch this. I think the standard way to do this would be an option to fail the maven build if any asciidoctor warnings occur. Any opinions?

**Comment by abelsromero** [comment]
This is a debated topic and is related to how asciidoctor (the core module) handles errors scheduled for  the next major release (v 1.6.0). For you to know, the main thread is here https://github.com/asciidoctor/asciidoctor/issues/44, you'll see the idea is to be able to obtain some final report on the status of the conversion.
With that information then it would be possible to take decisions like fail/no-fail.

**Comment by abelsromero** [comment]
This is a debated topic that goes back to how asciidoctor (the core module) handles exceptions.
You can check the main conversation here https://github.com/asciidoctor/asciidoctor/issues/44. The idea is that the core generates some report that other tools can consume, for instance, to take decisions like fail vs no-fail.
This is currently scheduled for next major release (v 1.6.0), but no date or confirmation can be provided.

**Comment by mojavelinux** [comment]
This will require a change core, as @abelsromero mentioned.

As a workaround, you can have your CI output scan the output for Asciidoctor warnings and errors and fail the CI build if one of these common prefixes is detected.

**Comment by Tillerino** [comment]
Great, thx for your quick replies!

**Comment by abelsromero** [comment]
Related to https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/178

**Comment by ptahchiev** [comment]
Guys, this seriously is a **must**. I have a very large documentation that incudes java snippets almost everywhere and when we do refactoring those snippets are gone and documentation is unusable. It is an absolute MUST that the jenkins must fail the build if a given snippet cannot be included.

**Comment by mojavelinux** [comment]
I hear you that it's important. To do this right, though, we have to properly log messages so that they are accessible to integrations. Trying to get at them by modifying the stderr object is just not the way to go about it.

Fixing this issue is the top priority for the 1.5.7 core release. See https://github.com/asciidoctor/asciidoctor/issues/44

You may be interested in talking to @vogella and @fap- about how they put an interim solution in place for the Gradle plugin. But that should been seen as only a temporary solution until we are logging messages to a logging system.

Having said that, there are still going to be many things that the processor does not check for. It's important to remember that the processor is looking for valid syntax, and only logging when something gets in the way. It's an absolute necessity to have a dedicated validator that supplements the processor. I am in the very early stages of working on that right now. I'll put something up as soon as I have a prototype.

**Comment by mojavelinux** [comment]
> This is currently scheduled for next major release (v 1.6.0), but no date or confirmation can be provided.

It's now scheduled for 1.5.7, which should be out before the end of the summer or early fall...and sooner if possible.

**Comment by ptahchiev** [comment]
Thank you Dan.

**Comment by Tillerino** [comment]
That is great news, thanks.

**Comment by gclayburg** [comment]
Does anyone have a workaround for Jenkins/ maven based builds?  Maybe something that could fail the build if it encounters "asciidoctor: WARNING:"  ?

**Comment by gclayburg** [comment]
ok, for anyone else having this issue, I configured [Jenkins Warnings plugin](https://wiki.jenkins.io/display/JENKINS/Warnings+Plugin?focusedCommentId=54723619) to make the build unstable when it sees any warnings matching this pattern.

In my case, my build is defined with a [Jenkinsfile](https://jenkins.io/doc/book/pipeline/jenkinsfile/) pipeline.  I can now add a build step that reads the console output of prior commands like this:

```
sh "mvn clean install"
step([$class: 'WarningsPublisher', canComputeNew: false, canResolveRelativePaths: false, categoriesPattern: '', consoleParsers: [[parserName: 'asciidoctor-warning']], defaultEncoding: '', excludePattern: '', failedTotalAll: '1', healthy: '', includePattern: '', messagesPattern: '', unHealthy: '', unstableTotalAll: '0'])
```

This uses a asciidoctor-warning parser that I configured in the Warnings plugin configuration screen.  I used this for the "regular expression" field:
`^\s*(.*)\s*(asciidoctor: WARNING:\s*)(.*):\s*line\s*(\d+):(.*)$`

And this for the "mapping script" field:

```
import hudson.plugins.warnings.parser.Warning

String fileName = matcher.group(3)
String lineNumber = matcher.group(4)
String category = "unused"
String message = matcher.group(5)

return new Warning(fileName, Integer.parseInt(lineNumber), "asciidoctor Parser", category, message);
```

**Comment by mojavelinux** [comment]
Thanks for sharing!

In case you haven't seen it, Jeremie documented something similar on his blog.

https://jmini.github.io/blog/2017/2017-06-25_asciidoctor-watch-build-log.html

**Comment by gclayburg** [comment]
oh cool, thanks for that link.  His regex looks a little more complete than the one I was using.  I guess I haven't seen any ERROR messages yet - Ha! - I'm sure I'll find a way to generate one sooner or later.  Maybe someone should package this up and create a PR for the Jenkins Warnings plugin?  It would be nice to be able to just select from a list of predefined parsers.

**Comment by hho** [comment]
> It's now scheduled for 1.5.7, which should be out before the end of the summer or early fall...and sooner if possible.

Sneaky @mojavelinux hasn't put a year… :grin: 

Unfortunately, I don't know Ruby. Is there any way I can help on the Java side of things?

**Comment by mojavelinux** [comment]
The development and release of Antora bumped the schedule for 1.5.7. But it also added additional motivation to get 1.5.7 released since we need it for Antora 1.0.

Coding this change is the easy part which I can handle. The important part that any developer can do is help with the requirements and design. The reason I haven't moved on it yet is that we still haven't figured out the right design for this feature. See https://github.com/asciidoctor/asciidoctor/issues/44

For example, I think that document problems should be stored on the document itself and only general problems would be routed to the logger. Otherwise, we lose important context for document-related problems.

**Comment by abelsromero** [comment]
Should be, but can't confirm yet. Right now we are waiting for the official 1.5.7 release and the AsciidoctorJ integration, which is already in the works https://github.com/asciidoctor/asciidoctorj/pull/641.

**Comment by mojavelinux** [comment]
There's a related change in AsciidoctorJ to expose the LoggerManager / Logger (and hook it to Java logging by default). By providing your own logger, you can essentially trap the warnings and errors and make a determination of how to handle them. See https://github.com/asciidoctor/asciidoctorj/pull/641

I'm also proposing exposing a max_severity property that reports the highest severity that got reported (so you don't even need to have your own logger impl...just check this property). This makes it even easier to control exit status. See https://github.com/asciidoctor/asciidoctor/pull/2674

**Comment by abelsromero** [comment]
After some testing we can now say that the new release will include this feature. So let's use this issue to discuss how to expose this feature.

My proposal (open for discussion in all aspects) is to include a new section in the configuration like this:
```
<messages>
	<consoleOutput>true</consoleOutput>
	<abortOn>
		<level>WARNING</level>
		<text>super-important-document.adoc</text>
	</abortOn>
</messages>
```
* `consoleOutput`: enables and disables printing the messages to the console in a similar way as they are show now (format will slightly change however). Default -> false
* `abortOn`: allows defining the conditions under which the build will stop and report as failed. There are two options. Setting both with require both to be met at the same time to abort.
* `level`: level of the message. That way users can decide if he build should abort on WARNING or ERROR for example.
* `text`: whether it should fail if the message contains a specific text. For instance if you want to abort on specific type of error (e.g. include) or on specific file (since the message contains the filename). Likewise we could add a multi-valued field to specify only filenames, but that seems to introduce too much complexity in the configuration XML.

//cc @jmini: iirc you worked on a plugin to implement this in Jenkins, your feedback will be very more than welcome.

wdyt?

**Comment by mojavelinux** [comment]
I like where you're going with this. Let's work on the naming a bit.

* Instead of `consoleOutput`, I think it should be `outputToConsole` (we shouldn't mix nouns and verbs in the option names); Maven tends to use verbs for options
* Instead of `abortOn`, I think it should be `failOn` (or `failIf`) to share consistent terminology with the asciidoctor command (this is also similar to the surefire test goal, which is a good source of inspiration)
* Instead of `text`, it should be `match` or `matchesText`. Just `text` is too ambiguous. But I like the idea.

I'm not sure about the name `messages` as the container. That doesn't communicate to me what we are controlling. Perhaps something like `messageHandler`? hmm Not sure.

**Comment by mojavelinux** [comment]
Oops, didn't mean to close. I had a mindless moment :pray:

**Comment by abelsromero** [comment]
> I'm not sure about the name messages as the container. That doesn't communicate to me what we are controlling. Perhaps something like messageHandler? hmm Not sure.

Me too. I'll see if something springs up in my mind. One thing for sure is I want to keep this options in an element instate of flat options at <configuration>.
So far I'd keep messageHandler and the other proposals are current options.

**Comment by mojavelinux** [comment]
>  One thing for sure is I want to keep this options in an element instate of flat options at .

:+1:

**Comment by jmini** [comment]
> //cc @jmini: iirc you worked on a plugin to implement this in Jenkins, your feedback will be very more than welcome.

You are referring to this blog post: [Asciidoctor: watch you build log](http://jmini.github.io/blog/2017/2017-06-25_asciidoctor-watch-build-log.html). The trick there is to configure the [Warnings
 plugins](https://plugins.jenkins.io/warnings) to parse the log produced by the asciidoctor-maven-plugin.

To make eveything more robust, I think the `asciidoctor-maven-plugin` should produce a structured file (xml, json) containing all the detected warnings, issues. I have opened this [blog post](https://medium.com/@j2r2b/reporting-source-code-issues-as-xml-or-json-80eff46776ab) to expose which format could be used. It could be something else. Then the Jenkins Warnings plugin could be extended to load the issues from this file.

Maybe this should be discussed in a separate topic, because the requirement is not to change the maven build status, but to create a structured report of all the findings.

**Comment by mojavelinux** [comment]
@jmini I think it might be possible to accomplish both...or at least this change may lay that foundation for what you are proposing.

Where we currently have: `<consoleOutput>true</consoleOutput>` (or `<outputToConsole>true</outputToConsole>`) perhaps instead we should have something like target, where target can be STDOUT, STDERR, a log file, etc.

Then, we could also have something like `<formatter>` that determines how the messages are formatted. One of those could be `xml` (or some schema name).

All that makes me think that perhaps the category for this section should be named `<messageAppender>`.

**Comment by abelsromero** [comment]
> Then, we could also have something like <formatter> that determines how the messages are formatted. One of those could be xml (or some schema name).

I am thinking we could provide that with a plugable component. Some interface that others can extends and add as a dependency to the maven plugin.


> All that makes me think that perhaps the category for this section should be named <messageAppender>.

I was just thinking about simply `logHandler`. It's not as semantic as I'd like, but it's easy to grasp for users and it's a direct reference to the AsciidoctorJ component.

**Comment by mojavelinux** [comment]
> I am thinking we could provide that with a plugable component. 

Exactly. I'm thinking it would be something like a fully-qualified class name (just like a logging appender).

...in fact, we should try to borrow as much as we can from the logging world.

**Comment by mojavelinux** [comment]
> I was just thinking about simply logHandler. It's not as semantic as I'd like, but it's easy to grasp for users and it's a direct reference to the AsciidoctorJ component.

I could get behind that.

**Comment by jmini** [comment]
Sorry to ask a naive question, but the `formatter` that we discussed, I think it should be in AsciidoctorJ and not in the maven-plugin... If I move my build to gradle, I want to be able to have the same output xml file.

If I run Asciidoctor from a simple java main, I also want to be able to plug my formatter there.

> plugable component

I think it should be registered as the asciidoctor macro, using the service registry provided by java.

**Comment by mojavelinux** [comment]
I'm not sure about registering it as a macro, but otherwise I agree. It seems like something that would fit in AsciidoctorJ as a built-in formatter. You'd still enable it in the plugin by name (probably class name, like you would a built-in logger appender).

**Comment by abelsromero** [comment]
> would fit in AsciidoctorJ as a built-in formatter

If so, does it make sense in asciidoctor itself?

**Comment by jmini** [comment]
> registering it as a macro

I meant using the java service provider interface like macro uses `META-INF/org.asciidoctor.extension.spi.ExtensionRegistry`, but of course the formatter needs to implement an other java Interface.

**Comment by mojavelinux** [comment]
> I meant using the java service provider interface

That's what I figured you meant. :+1:

**Comment by mojavelinux** [comment]
> If so, does it make sense in asciidoctor itself?

I don't think so. At least, not yet. I'd rather prototype this closer to where it is used in the Java / CI / build world. Then, when we find that we have something that should be available everywhere, then we could promote it up into core. For now, I'd rather keep core as something that is strictly API-based.

**Comment by stianlagstad** [comment]
Hey guys! This is a feature I'd very much like to see. Is there a way I (as a new contributor) could help?

**Comment by abelsromero** [comment]
Sure @stianlagstad! The PR was just merged into asciidoctorJ (https://github.com/asciidoctor/asciidoctorj/pull/643). If you want, just install it locally and start a POC branch, create a PR that we can use to discuss.
Experiment and do not hesitate to ask.

**Comment by ptahchiev** [comment]
Any news on this? The asciidoctorJ issue was fixed about a year ago

**Comment by abelsromero** [comment]
Thanks for noticing! I'll close this issue.
The feature is available since [v1.5.7](https://github.com/asciidoctor/asciidoctor-maven-plugin/releases/tag/asciidoctor-maven-plugin-1.5.7). Check the `logHandler` configuration in the README.
Note also, you can inject your custom handler to generate other kinds of reports. I am aware @jmini has had some success generating reports for Jenkins.

**Comment by ptahchiev** [comment]
Hi @abelsromero does this also work with the `maven-site-plugin`? Where do I put the `logHandler` configuration?

**Comment by abelsromero** [comment]
I am afraid this is not compatible with the site.
But it could be added if I can inject the main configuration.

**Comment by wimdeblauwe** [comment]
If there are others like me that arrive here via Google and wonder how to configure it, add this to your Maven configuration:

```
                <plugin>
                    <groupId>org.asciidoctor</groupId>
                    <artifactId>asciidoctor-maven-plugin</artifactId>
                    <version>${asciidoctor-maven-plugin.version}</version>
                    <configuration>
                        <logHandler>
                            <outputToConsole>false</outputToConsole>
                            <failIf>
                                <severity>ERROR</severity>
                            </failIf>
                        </logHandler>
                    </configuration>
```

This will make the build fail if Asciidoctor produced an ERROR. The `outputToConsole` set to `false` ensures that the error is not printed twice in the Maven output.

(Would be nice if this was the default I think)

**Comment by vogella** [comment]
See also https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/536 for the same configuration in Gradle builds. 

(This one is easier to find via Google search).
