### ISSUE TITLE
Bump to AsciidoctorJ 1.5.4

### ISSUE THREAD

**Issue by leif81** [asciidoctor/asciidoctor-maven-plugin#271]
Asciidoctor and AsciidoctorJ version 1.5.4 were released in January. Proposing this project move to that version and cut a release.

There's at least one issue, asciidoctor/asciidoctor#1582, that I'm really looking forward to seeing fixed by moving to that version.

**Comment by abelsromero** [comment]
We are aware :disappointed:  and we are working on it. Current scenario is that we found an issue in AsciidoctorJ (https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/258) which is fixed in AsciidoctorJ 1.5.4.2 but it is not published yet, because we want to close some points before publishing it.

In the meantime, you can directly upgrade the AsciidoctorJ version in the plugin, see the example below. Unless you're using some extensions you'll be fine, and even in that scenario, you can try the preview version of AsciidoctorJ `1.6.0-alpha.3`.
https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml#L33-L37.

**Comment by leif81** [comment]
> In the meantime, you can directly upgrade the AsciidoctorJ version in the plugin,

Thankyou that worked well :+1:

**Comment by abelsromero** [comment]
In that and if you don't mind, I'll close the issue.
