### ISSUE TITLE
Aggregate README.adoc from multiple repos within the same GH Org

### ISSUE THREAD

**Issue by richnsoos** [asciidoctor/asciidoctor-maven-plugin#275]
Currently, we pull README.adoc files that are distributed across **multiple modules within a single repo (in a single GH org)** and aggregate and publish all content into a single format (HTML).

It is possible to pull README.adoc files that are distributed across **multiple repos in a single GH org** and aggregate and publish all content into a single format?

Is it possible to pull README.adoc files that are distributed across **multiple repos in multiple GH orgs** and aggregate and publish all content into a single format?

How do we achieve this?

**Comment by Mogztter** [comment]
Hello @richnsoos 

What about the `include` macro ?

```
= Main
:uri-asciidoctor-gh-org: https://raw.githubusercontent.com/asciidoctor
:uri-bk2204-gh: https://raw.githubusercontent.com/bk2204

include::{uri-asciidoctor-gh-org}/asciidoctor-maven-plugin/master/README.adoc[]

include::{uri-asciidoctor-gh-org}/asciidoctor.js/master/README.adoc[]

include::{uri-bk2204-gh}/dev-practices/master/README.adoc[]
```

**Comment by abelsromero** [comment]
I am not sure about the question. Do you mean if the maven plugin provides a way to automatically download remote AsciiDoc files to incorporate during the build process?
If it so, I am afraid the answer is no. As @Mogztter pointed out you can use the include macro, or also if you want to make clear that the document is somewhere else, you could write an Include extension to do something like `github-remote::repo/file-path.adoc[]`.

If what you need is not to include, but simply download the files to render them, I found this thread with some maven options http://stackoverflow.com/questions/2741806/maven-downloading-files-from-url.
I'd suggest to use the maven-resources-plugin to copy what you need from the main project to a staging directory, then download external resources, and finally render it. That way you avoid downloading files in the sources area.

**Comment by richnsoos** [comment]
Thanks both. Yes, @abelsromero , that is what we want to do -- use the asciidoctor maven plugin to specify multiple input locations (ie: multiple sourceDirectory config options) to download remote AsciiDoc files from different projects (ie: repos in GH) to incorporate during the local build process. Since there are [multiple outputs for the same file](https://github.com/asciidoctor/asciidoctor-maven-plugin#multiple-outputs-for-the-same-file), I thought/wished there would be multiple inputs for the same output. :-)

Wonder how other large projects with multiple repos (where the documentation is kept close to code in each repo) are aggregating it all in a single build process?

**Comment by abelsromero** [comment]
> Wonder how other large projects with multiple repos (where the documentation is kept close to code in each repo) are aggregating it all in a single build process?

We have had some similar discussions about that also. We wanted to centralize some documentation that right now is duplicated in many repos. So far the conclusions were that we needed to delegate on some other solution to do the download/prepare tasks because is not part of asciidoctor scope to deal with infrastructure.

Now, using only maven is achievable but a bit cumbersome. Simpler options than the ones I mentioned before are using gradle ([example](https://github.com/asciidoctor/asciidoc-grammar-prototype/blob/master/build.gradle#L55-L69)) or some bash script to do that.
About the bash option, you could execute it using this http://www.mojohaus.org/exec-maven-plugin/ during the `generate-resources` phase, and render the documents during `process-resources`.

Other than that, I cannot offer much more.

**Comment by richnsoos** [comment]
hi @abelsromero , just wondering if anything new has become available that would support multiple sourceDirectories? I realize this is a closed question, but just thought I would check in.

**Comment by abelsromero** [comment]
No, the stance remains the same, sorry.
Retrieval of source files from other locations is not something we consider in our scope, specially when other tools can do that much better.

But I am curious about the use case, what prevents you from using a plain `include::` or building a custom extension?

**Comment by richnsoos** [comment]
hi @abelsromero , sure. i understand. thanks for responding so quick. we currently use include:: to successfully bring in different content spread across different sub modules within a SINGLE repo. However, our content is spread across multiple repos. currently, using the asciidoctor maven plugin, we are constrained or forced to have a single generated HTML file for each one of our repos. however, our need is to have a single generated HTML file for adoc content that is spread across multiple repos. A common customer complaint is that our content is hard to find (ie: scattered) and not searchable.

**Comment by richnsoos** [comment]
we love using this plugin to take as input all our adoc files that sit very close to code (and therefore scatter, to the customer's point) and package it into a single HTML file that we publish to our website, which allows for searchability.

**Comment by abelsromero** [comment]
Keep in mind that Asciidoctor is designed with the idea of generating a single output. In fact, once I tried to adapt the plugin to be able to define different sources in a project, but we discarded because it added more complexity but no new features. You can do the same with maven executions, and that has been my approach since then.

And if I understand your needs correctly, I think you could do the same. Let me draw the scenarios I understand you can have and please, do correct me if I am wrong.
*I am ignore who starts the process.*
*Arrows represent includes and red dots, documents or origin*
*I am ignore other resources like images*
![image](https://cloud.githubusercontent.com/assets/5781153/26464305/980e463e-4187-11e7-819d-113a280a4bad.png)


**Repo 1**: 5 independent documents that should generate 5 HTMLs.
**Repo 2**: 5 files with internal includes that should generate 2 HTML.
**Repo 3**: 5 files with external includes that should generate 5 HTML.

To render all of them in a single run, you should seat -at least- 1 independent maven execution for each project with different setups.
**Repo 1**: just use `sourceDirectory` + `baseDir`  or `preserveDirectories` depending on your layout.
**Repo 2**: in that case you'll likely have to setup two different executions.
**Repo 3**: again, just setup a `sourceDirectory` + ....

Remember you can prefix hidden files with an underscore (_) and they are ignored. I use this for documents that I know will always be part of another, like the three included documents in Repo 2. With that trick you can can alleviate some configuration and just setup a sourceDirectory.

Also, I just remembered there's a way to create link between GH repos https://github.com/blog/2104-working-with-submodules, maybe you could create an aggregate project that collects the docs from others and offers a single view. I've never used them, but could be worth a try in your case.

**Comment by abelsromero** [comment]
Clossing for stalled. Feel free to re-open or open a new issue referencing this one of there are still questions.
