### ISSUE TITLE
How to configure the equivalent of the fo-pdf file for pdf generation?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-maven-plugin#284]
In this SO question I mention the fo-pdf.xml file, to configure the pdf output:

http://stackoverflow.com/questions/34992879/how-do-i-merge-or-even-disable-footnote-links-in-asciidoc-fop/41352286#41352286

What is the equivalent config file with asciidoctor-maven-plugin?

**Comment by abelsromero** [comment]
Not sure I understand the question, please correct if I am wrong.
To me, the post seems related to AsciiDoc/Python implementation, and the issue for the poster is that during the DocBook -> PDF conversion, normal hyperlinks are converted into footnotes.

I tested the same case using the asciidoctor-pdf gem and the issue does not happen. Links are shown as links in the PDF, so no need to add anything to remove them. On the other hand, on the topic of footnotes Asciidoctor offers a way to reference the same footnote (see `footnoteref` http://asciidoctor.org/docs/user-manual/#user-footnotes). But sadly, footnotes are inlined in the PDF, pending proper implementation (https://github.com/asciidoctor/asciidoctor-pdf/issues/73).
You can still use the asciidoctor-maven-plugin to convert the AsciiDoc sources to docbook and then use the `docbkx-maven-plugin` to convert the output to PDF. I recall seeing this done a long time ago, but couldn't find where and I am not familiar with that other plugin. That means that in order to set those parameters you'll have to check the other plugin :/ sorry.

Does it help you?

**Comment by mojavelinux** [comment]
Using the Asciidoctor Maven plugin, you have two choices to get to PDF. You can either configure it to generate a PDF using Asciidoctor PDF, which is supported out of the box. Or you can configure the plugin to generate DocBook, then use any of the available Maven DocBook plugins to generate PDF from there.

You can see both examples in the Maven examples repository. https://github.com/asciidoctor/asciidoctor-maven-examples

**Comment by mojavelinux** [comment]
In other words, the customization you are looking to apply must be made to the DocBook Maven plugin. The docbkx-maven-plugin seems to be easiest to use (at least, it was when I last tried it).

**Comment by seinecle** [comment]
Thanks a lot, I am going t try the docbkx-maven-plugin route. Too bad the Asciidoctor Maven plugin does not support custom fo.xsl via something like `<foCustomization>src/docbkx/docbook-fo.xsl</foCustomization>`

**Comment by mojavelinux** [comment]
Actually, it's not too bad at all. It's quite intentional. Plugins are
meant to be composed. It would be out of scope for the Asciidoctor plugin
to manage and execute the DocBook toolchain. We'd be mixing
responsibilities that shouldn't be mixed. And it's no small task.

Having said that, I'd be glad to improve the example project so that it's
easier for someone like yourself to come along and setup the pipeline.
Suggestions welcome.

**Comment by seinecle** [comment]
Well said :-) Copy pasting relevant sections of the pom from the example project, I'll see how it goes

**Comment by seinecle** [comment]
Wow ok, the rendering works! It is different and customizing it will take some time - but I'll be able to control every aspects of formatting - thanks!
Btw, my use case will be:

- keeping Asciidoctor PDF to create the pdf version of single tutorials
- docbkx-maven-plugin to create the book version of all tutorials collated together, which needs more customization.
