### ISSUE TITLE
"true" attributes are replaced by ""

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-maven-plugin#288]
If you set attribute values to true inside the POM, they are falsely replaced by "".

E.g., setting

```xml
<revealjs_controls>true</revealjs_controls>
```
leads to 
```js
Reveal.initialize({
  // Display controls in the bottom right corner
  controls: ,
```
making JS complain about the `,` instead of an expected value of true or false.

This results in an empty slide show.

As far as I can see the problem occurs in AsciidoctorMojo.java line 496.

**Comment by mojavelinux** [comment]
The behavior of the plugin is actually correct. In Asciidoctor, an attribute value of true is represented as an empty string. The Reveal converter should account for this and emit the value of "true" instead of the value of the attribute. Therefore, I think this issue needs to be raised in the Reveal converter.

**Comment by ascheman** [comment]
Besides my personal workaround in a plugin fork I have raised an additional issue in the reveal converter: asciidoctor/asciidoctor-reveal.js#125

**Comment by mojavelinux** [comment]
Thanks Gerd! We'll get to the bottom of it.

**Comment by mojavelinux** [comment]
The workaround is to use the value 1 and 0 instead of true and false. That works with the code as it is.
