### ISSUE TITLE
Remove default value for imagesdir configuration.

### ISSUE THREAD

**Issue by sjoerdtalsma** [asciidoctor/asciidoctor-maven-plugin#296]
This default value (`"images"`) caused some issues where documents were no longer able to specify an `:imagesdir:` attribute. For details, see the comments in #294, which has been resolved by at least making the default overridable.

What should happen for version `1.6.0`:
- [ ] Rename the setting from `imagesDir` to `imagesdir` to correspond to the attribute name.
- [ ] Remove the default value from the maven plugin configuration as defaults (if any) should be specified by asciidoctor core and not the maven plugin.

**Comment by abelsromero** [comment]
Just for the record...

I run some -unsuccessful- tests to see if we can get IDE auto-completion for properties inside the `<attributes>` section while allowing to add any attribute freely.
In order to get some auto-completaion, instead of defining attributes as a Map<String, Object> inside the Mojo I created a custom class (called AttributesMap) that extended from HashMap<String,Object> and added a custom `setImagesdir(String)` method.
The results are:
 - It seems IntelliJ does not recognize properties inside classes in any way. It's the same for the `resources` block, it does not provide any help (opened a [post ](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000160090-Auto-completion-of-Maven-configuration-properties-inside-beans)to ask about it).
- Eclipse does recognize them under some cases:
        It is able to recognize properties in normal beans provided the set method is present. No need to additional annotations.
        It does not recognize them when the class extends HashMap. That is, when `AttributesMap` only contains setters it works (shows the images property), as soon as I add the `extends HasMap` clause, eclipse does not provide any help.

**Comment by tsegismont** [comment]
@sjoerdtalsma this workaround helped me http://asciidoctor.org/docs/user-manual/#configuring-attributes-for-awestruct

**Comment by sjoerdtalsma** [comment]
@tsegismont Thank you for the well-intended workaround. I was aware of it (see #294 😉) but was advised to open this issue to get it fixed properly for `1.6.0`.

**Comment by tsegismont** [comment]
All is well then ! 😀

**Comment by mojavelinux** [comment]
What's the verdict with this issue?

**Comment by abelsromero** [comment]
Scheduled for 1.6.0 since it breaks backward compatibility.
Since there's not much on the maven side for 1.5.8, maybe if it makes sense to skip it and start working for 1.6.0.

**Comment by mojavelinux** [comment]
Excellent. Though I would recommend that you start looking towards 2.0.0 (and semantic versioning) instead of 1.6.0. I'll be posting information on the list about this shortly, but the main message is, 2.0.0 is planned before the end of the year.

**Comment by gebezs** [comment]
I am using 1.6.0 and the `{imagesdir}` is still set to `images`.
Is this postponed or will the maven plugin behave differently in the future?
In case of removal will there be any backward compatible solution?
I am using the `.asciidoctorconfig` to make the Idea plugin behave as the Maven plugin.
Will the Maven plugin support the same config mechanism?

My `.asciidoctorconfig` config:
```
#ifndef::imagesdir[:imagesdir: images]
```

**Comment by mojavelinux** [comment]
I believe 2.0 is a good opportunity to change this.
