### ISSUE TITLE
plugin 1.5.5 uses platform encoding for filtering resources

### ISSUE THREAD

**Issue by ecki** [asciidoctor/asciidoctor-maven-plugin#305]
Since 1.5.5 (as opposed to 1.5.3) the `process-asciidoc` goal will also copy (filtered) resources. It prints:

```
[INFO] --- asciidoctor-maven-plugin:1.5.5:process-asciidoc (asciidoc-to-pdf) @ troubleshooting-manual ---
[DEBUG]   (s) resources = []
[DEBUG] properties used {...project.build.sourceEncoding=UTF-8}
[INFO] Using 'Cp1252' encoding to copy filtered resources.
[INFO] ignoreDelta true
[INFO] Copying 0 resource
[INFO] Rendered d:\....adoc
````

Where `Cp1252` is my (Windows) platform encoding but not the encoding I have configured for the POM via `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>` (debug output confirms it is set).

I guess it is not that critical as most of those resources are not filtered anyway, but it does look like it is missing to define and propagate a `<encoding>` configuration (to resource copy as well as potential asciidoc file encoding?).

Env: Maven 3.5.0 on Windows 10 x64 german with Java 1.8.0_141 with explicite asciidoctorj 1.5.6 and jruby 9.1.8.0.

**Comment by abelsromero** [comment]
good catch! I created a PR to capture the property https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/306

Note that resources are just copied, filtering is disabled.
Thing is we use `Maven Filtering` under-the-hood to copy the resources because it allows for some nice options (see <resources> section in the [README](https://github.com/asciidoctor/asciidoctor-maven-plugin#configuration-options)). The API does not allow to separate the copy logic from the filtering one, so we disable the filtering. But still, it prints those message.
Back then I tried to disable them, but could not find how, let me have a look again, and maybe I can disable them.

**Comment by abelsromero** [comment]
Really, haven't been able to find anything to disable the messages, the code is pretty straight forward, nothing weird, no config files, nothing... Also modifying the logger is not possible and I don't like it anyway.
I checked the code of the `maven-resource-plugin` and there's nothing there either, but the plugin does show much less messages in the console and uses the same API we do (head spinning here).

After all of this, I have sent a message to the mailing list, let's see how it goes.

**Comment by abelsromero** [comment]
Turns out, there was a new release of the `maven-filtering` that changes the messages from `info` to `debug`. That removes the excessive messages and aligns the console output to the last version of the maven-resour ces-plugin.

We go from
```
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] ignoreDelta true
[INFO] Copying 6 resources
[INFO] Copying file docs\asciidoc\docinfo.html
[INFO] Copying file docs\asciidoc\example-manual.adoc
[INFO] Copying file docs\asciidoc\images\sunset.jpg
[INFO] Copying file docs\asciidoc\subdir\_b.adoc
[INFO] Copying file docs\asciidoc\subdir\_c.adoc
[INFO] Copying file main\java\example\StringUtils.java
```
to
```
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
```

@ecki, @mojavelinux if it's fine for you, I'd upgrade the version in the same PR #306 and close this issue with it.

**Comment by ecki** [comment]
Fine with me. I think it is less confusing when the encoding would be the right one, but I agree that it probably does not apply.
