### ISSUE TITLE
Is this plugin thread safe?

### ISSUE THREAD

**Issue by shalugin** [asciidoctor/asciidoctor-maven-plugin#326]
I want to use parallel compilation in maven.

I have the following warning:
```

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in MapStruct Documentation:
[WARNING] org.asciidoctor:asciidoctor-maven-plugin:1.5.6
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

Is `asciidoctor-maven-plugin` thread safe?

**Comment by abelsromero** [comment]
Good question! We should test it and do some research to be 100% sure, but I am pretty sure the plugin is,
We comply to everything stated here (except for third libraryes, need to check): https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3
Afaik AsciidoctorJ is thread-safe (cc @robertpanzer ) and we don't keep anything in static variables.

The way I understand the documentation, Maven parallelises at module level not at Mojo level. And each execution of the mojo uses a new class instance of it in a single JVM.
Note that the warning comes because of the metadata descriptor, it is not doing any real analysis.

Have you experienced any issue? or do you have any more information on the matter?

**Comment by shalugin** [comment]
> Keep in mind that the warning is shown because of the metadata descriptor, it is not doing any real analysis.

Yes, I know it,
> Have you experienced any issue? or do you have any more information on the matter?

I don't have any issue. I just wanted to know is the plugin thread safe.

Thank you for answer!

**Comment by timkrueger** [comment]
It would be awesome if you can mark the asciidoctor-maven-plugin as thread safe. That will be remove a lot of unneeded logging in our build.
