### ISSUE TITLE
Trigger auto-reload on included files changing

### ISSUE THREAD

**Issue by mrm1st3r** [asciidoctor/asciidoctor-maven-plugin#403]
When starting the http server using `mvn asciidoctor:http asciidoctor:auto-refresh` it will only trigger a refresh on exactly the files being built.
But when building large documentation as single-page HTML, the main source files mostly contain includes to other files. When those included files are changed, no auto-refresh is triggered.

Example:
-  `sourceDocumentExtension` is set to "index.adoc"
- "howtos.index.adoc" includes "howto/writing-documentation.adoc"
- "howto/writing-documentation.adoc" is being modified

Expected behavior: rebuild is triggered and "howtos.index.html" will be updated
Actual behavior: No rebuild is triggered and I still have to type in refresh into the console.

**Comment by abelsromero** [comment]
The way it works is by adding a listener to the configured "sources" to minimize scanning all possible files. And I honestly would like to avoid scanning all files, not to mention that some people may use special file extensions or locations.

To do it right, we depend on https://github.com/asciidoctor/asciidoctor/issues/60. So, the only option I see right now is adding a parameter so that users can add a regex of additional files to scan using the command line. Something like `mvn asciidoctor:http asciidoctor:auto-refresh -Dmonitor=**/__includes/*.adoc`

**Comment by mrm1st3r** [comment]
OK, I think I understand. I think that command line argument could also be set as a configuration for the plugin inside the pom.xml? It could just default to the same value that determines which files are being built, but be overridden individually by users.

Having to remember the correct regex and supplying it each time to the command might be not the best option to encourage people to write or update documentation more often. :)

**Comment by abelsromero** [comment]
> OK, I think I understand. I think that command line argument could also be set as a configuration for the plugin inside the pom.xml

Can be done. About the semantics of the option, to make it simpler I think it would be better that the files defines by the regex are added to the documents configured through the other options. About the name, any suggestion?  I am between "listenTo" & "refreshOn"

**Comment by mrm1st3r** [comment]
I would go for "refreshOn" because it is then more obvious that it is used for "auto-refresh".

**Comment by abelsromero** [comment]
Adding this to next milestone. I experimented with IncludeProcessor, but no use, specially if someone is using a custom processors also.

**Comment by abelsromero** [comment]
Closed with https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/542
