### ISSUE TITLE
Paper size of PDF is always US Letter - please add config option to set paper size

### ISSUE THREAD

**Issue by jesperdj** [asciidoctor/asciidoctor-maven-plugin#410]
When I generate a PDF with asciidoctor-maven-plugin, the paper size is always US Letter and there does not seem to be a way to configure a different paper size. I would like to be able to set A4 (ISO standard paper size), for example.

Please add a configuration option to set the paper size.

**Comment by abelsromero** [comment]
This can be set in `page.size` in a theme configuration like in this example https://github.com/asciidoctor/asciidoctor-maven-examples/blob/7edd0ea9dfb6045a12a38fd52d9fa9b4250668f0/asciidoctor-pdf-with-theme-example/src/theme/custom-theme.yml#L8.

You can check here how to configure the theme, note the naming conventions so that the config file is recognized.
https://github.com/asciidoctor/asciidoctor-maven-examples/blob/7edd0ea9dfb6045a12a38fd52d9fa9b4250668f0/asciidoctor-pdf-with-theme-example/pom.xml#L87

And if you are interested in the other theming options, you can see them here https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

**Comment by mojavelinux** [comment]
A4 is now the default. Perhaps the version of Asciidoctor PDF you're using is old. Can you confirm which version you're on?

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L31

**Comment by jesperdj** [comment]
When I created this issue on GitHub a few days ago, I got an error page when I submitted the issue. So I assumed the issue had not been submitted. Now I see that it's here anyway.

I was indeed using an older version of Asciidoctor and after upgrading the paper size is indeed A4 by default.
