### ISSUE TITLE
Publish full documentation

### ISSUE THREAD

**Issue by OrangeDog** [asciidoctor/asciidoctor-maven-plugin#413]
There needs to be full documentation of all mojos and their configuration.
All I can find is documentation of `process-asciidoc` in a non-standard format.

**Comment by abelsromero** [comment]
While it's inexcusable they are not documented, that partially because there's not been demand for them. 
* On one side, ZipMojo is scheduled to be removed at some time.
* And on the other, the refresh/http mojo does not offer much compared to preview plugins for IDEs. These are legacy components for when no better tools were available for those use cases.

About the standard format, you mean like in a maven-site fashion?

**Comment by OrangeDog** [comment]
I have various snippets generated externally (specifically by Spring REST Docs) and wanted to get a better live preview. It looked like the http mojo would do that, but I couldn't get it to refresh as I wanted. Either periodically or by watching other directories. My attempt resulted in a constant loop of client-side refreshes instead.

> About the standard format, you mean like in a maven-site fashion?

Indeed. Some plugins (e.g. checksum-maven-plugin) also document their configuration in such a way that my IDE (IntellIJ IDEA) can show snippets when editing the POM.

**Comment by abelsromero** [comment]
The http and refresh mojos were redone and are fully supported/documented in readme now. Does this help?

**Comment by abelsromero** [comment]
The new docs in https://docs.asciidoctor.org/maven-tools.
Make a clear disctintion between site and plugin options. And for each mojo there's a dedicated section with all available options.

![image](https://user-images.githubusercontent.com/5781153/117512035-173d2780-af8f-11eb-8a39-160d09abd747.png)
