### ISSUE TITLE
How include README.adoc with images in another adoc file ?

### ISSUE THREAD

**Issue by ndywicki** [asciidoctor/asciidoctor-maven-plugin#419]
Hi team,

I try to aggregate all README.adoc from a Maven multimodules projects. In particular handle the images in differentes directories and the PDF generation.

Structure example:
```
root
├───module-doc
│   ├──src/docs
│   │  └──global.adoc
│   ├──src/images
│   └──pom.xml
├───module-a
│   ├──docs/images/image_a.png
│   └──readme.adoc
├───module-b
│    ├──docs/images/image_b.png
│    └──readme.adoc
└─pom.xml
```

In `global.adoc` I want include all `readme.adoc`:
````
include::../../../module-a/readme.adoc[leveloffset=+1]
include::../../../module-b/readme.adoc[leveloffset=+1]
````
And modules content images from theirs own sources directories (ie.  `:imagesDir: docs/images`)
Content example of `reamde.adoc` from `module-a`:
````
ifndef::imagesdir[:imagesdir: docs/images]
...
image::image_a.png[]
````

I use the lastest asciidoctor-maven-plugin version `2.0.0-RC.1`
Images are correctly resolved in each modules.
Texts are correctly displayed in the `globale.adoc` PDF output genration but without images resolved.

It's possible to handle this use case ?
Maybe I need to copy all images under a same target directory (like maven resources)
I tried many configurations and played arround imagesDir configuration.

The goal is to modularize the documentation like an maven independant module.

Thanks,
Nicolas

**Comment by abelsromero** [comment]
While I look into it, side question here:

> The goal is to modularize the documentation like an maven independant module.

Following also maven conventions, have you considered placing global under the parent project? This should simplify pathing.

**Comment by abelsromero** [comment]
Here is a working example (note it's a branch) -> https://github.com/abelsromero/asciidoctor-maven-multimodule/tree/feature/add_aggregator_example_issue_419.
It's in a generic repo I use for demo, so apologies for having more stuff, you can convert only the appropriate modules with `mvn clean generate-resources -pl aggregated-1 -pl aggregated-2 -pl aggregator`.

Also, note sure if the difference in the pathing of images in the aggregator was intentional, but the example complies with it.

**About the HTML conversion...**

This is the easy part, just keep in mind you that `images::` path will be translated to the value of `imagesdir` attribute + path in document.
So, it's a matter of using the `<resources>` to copy the files you need to the target you desire. Given the default value is _images_ in the maven plugin, I setup resources to create that directory in the target path.
The only complexity is in the sub-modules, converting the README in the same project relies on some hacks and if no include is defined, one needs to add an _exclude all_ to avoid copying the whole project into the target path.

**About the PDF conversion...**

Unlike in the HTML case, here the converter needs to access the images _during_ conversion. Tbh, this is not 100% you can embed images in HTML too if you need, so the case would be the same.
Back to PDF, that means, the path in the AsciiDoc documents must point to the file, so here we need to play with `ifdef` as you discovered.
But not only we need one path, we need 2 configurations, one for when rendering individually, and another for when rendering from the aggregator. So, using the default `ifdef::backend-pdf[]` to discriminate won't work here.
I mean.
See in the example how I set `pdf-single-conversion` and `pdf-aggregated-conversion` in their respective poms.
Getting the path can be tricky, but you can see the absolute path being build in the console, just look at it and adjust accordingly.
Sometimes you can just set `imagesdir` in the pom, but here for the aggregated PDF you need to override the value of `imagesdir` in every README.


**About the previews...**

If you want to play with preview, some plugins inject attribute to detect you are rendering from one. For example, in IntelliJ (best writing experience in my personal opinion :+1:).
See the details here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Conditional-Rendering
But keep in mind that the preview is another build configuration, maintaining previews can  ber big effort, and not always pays. Remember that your users will see the final converted version.
The preview of the aggregated doc does not work for the images in the second module because -like in the pdf- we would need to define another attribute for the case "preview + aggregated". The current solution overrides the value of imagesdir in the second document with the path for single preview.


**Important**
* Note the subtleties in how `<resources>` are set in the submodules.
* Regarding custom attributes, you can use nested ifdefs or attributes with different values. But I prefer to keep things simple and more expressive with an attribute for each condition. So if I need to express a double condition (here "pdf && singe/aggregated") I define an attribute for each combination.
* I used short notation in the second module, just to show it.

_If there's any issue, doubt do not hesitate to ask._

**Comment by ndywicki** [comment]
Inspired by your example, I managed to do what I wanted 👍 

Finally the key is the configuration of the resource to copy all the images in the target image, and remove any other configuration of `imagesDir`.

I just keep the macro `ifdef::env-idea[:imagesdir: src/docs/images]` in sub-documents for rendering in IDEA.

I also encountered a strange behavior with PlantUML and the PDF backend, I did not render the image but the code block though ok with HTML5.

I had to add the requirement `<require>asciidoctor-diagram</require>`  in the PDF module in addition to the global attributes of the asciidoctor-maven-plugin and specified the `imagesdir` :

````xml
<execution>
  <id>asciidoc-to-pdf</id>
  <phase>generate-resources</phase>
  <goals>
      <goal>process-asciidoc</goal>
  </goals>
  <configuration>
      <requires>
          <require>${project.basedir}/src/docs/themes/dracula.rb</require>
          <require>asciidoctor-diagram</require>
      </requires>
      <backend>pdf</backend>
      <attributes>
          <imagesdir>${project.build.directory}/generated-docs/images</imagesdir>
          <toc />
          <toclevels>3</toclevels>
          <sectnums/>
          <pagenums />
          <pdf-style>${user.dir}/src/docs/themes/pdf-theme.yml</pdf-style>
          <pdf-fontsdir>${user.dir}/src/docs/themes/fonts/pdf</pdf-fontsdir>
          <chapter-label/>
      </attributes>
  </configuration>
</execution>
````

Many thanks,
Nicolas

**Comment by abelsromero** [comment]
> I also encountered a strange behavior with PlantUML and the PDF backend, It did not render the image but only the source code block though ok with HTML5.
> 
> I had to add the requirement `<require>asciidoctor-diagram</require>` in the PDF module in addition to the global attributes of the asciidoctor-maven-plugin and specified the `imagesdir` :

That should be the default behavior. I tried to render  an HTML withouth `<require>` and it did not generate the conversion.
