### ISSUE TITLE
define all maven properties as attributes

### ISSUE THREAD

**Issue by jyterrien** [asciidoctor/asciidoctor-maven-plugin#489]
Thank you for taking your time to talk with us!
- [ ] Bug report
- [X] Feature request
- [ ] Question

**All maven properties**
Could we not define an element of conf
propertiesAsAttributes = true / false
which when true adds all maven properties as attributes in asciidoc.
It is laborious to systematically pass dozens of properties in the conf.
`

    <configuration>
        <sourceDirectory>src/docs/asciidoc</sourceDirectory>
        <outputDirectory>target/docs/asciidoc</outputDirectory>
        <backend>html</backend>
        <doctype>book</doctype>
        <propertiesAsAttributes>true</propertiesAsAttributes>
        <attributes>
            <stylesheet>my-theme.css</stylesheet>
        </attributes>
    </configuration>
`

Bye

**Comment by abelsromero** [comment]
All maven properties should be already passed as attributes with dots being replaced by hiphens as describred in `attributes` in the [Configuration section of the readme](https://github.com/asciidoctor/asciidoctor-maven-plugin#configuration) since v2.1.0. Note that values in the `<attributes>` section take precedence over those in `<properties>`, so that if one is set in both, the value applied is the one in `<attributes>`. This allows setting custom defaults in multi-module or multi-execution builds.

Said that, that only applies to strict Asciidoctor attributes. Things like `sourceDirectory`, `outputDirectory`, `backend` are "options" in Asciidoctor terms. Those can be set using command properties like in `mvn compile -Dasciidoctor.outputDirectory=another/path". For those, it should be possible to define defaults using maven `<pluginManagement>` section.

**Comment by jyterrien** [comment]
Thank
my configuration is from an old version and I had not seen this feature

the subject is therefore closed.
