### ISSUE TITLE
Q: image directory management

### ISSUE THREAD

**Issue by smt-mj** [asciidoctor/asciidoctor-maven-plugin#497]
[Question]

Hi,

i am oprganising my projects and subchapters (containing aodcs that will be included) in folder like this:

- docs
-- images
-- csv
-- chapter
--- [subchaptername]
---- images
---- csv

on the level of docs there is a content adoc and a render adoc that includes the content adoc, so he content adoc does not need to know about all the adoc text formating headers.

it also includes all the subchapter-adocs. what i encountered is, that i must do specific imagedir definitions in the start of subchapter documents, or the main.adoc wont find the images from the subchapter image folders, because the included text from subchapters want to target the docs/image folder instead of the docs/chapter/subchaptername/images.

so my current solution is that i do this:

``` adoc
:imagesdir: {docdir}/images
ifdef::maindocument[]
:imagesdir: {docdir}/../../target/docs/chapter/doc-system/images
endif::maindocument[]
```

so i must check if this docuemtn gets rendered by itself or if it was included into a main document (by checking the maindocument variable, which is only existent in the main.adoc) and per condition set the imagedir.

why must i do that?

also i just encountered that if i include an chpater, which changes the imagedir variable. And afterwards i want to show another image in the main adoc, then the imagedir is still set for the image folder path of the included documents images. so i must reset the imagedir back to the main.docs image dir, so that the images after the include section of the chapter adoc are able to find their images... this is so frustrating.

am im doing something wrong?

thanks & cheers

**Comment by abelsromero** [comment]
I think I don't fully understand the problem, but I suspect is related to preview and ability to see images in the included subchapter adocs? Is that so?

**Comment by smt-mj** [comment]
not in preview.
but in rendering.

the example is **src/docs/main.adoc** includes (src/docs/)**chapter/chap1/chap1.adoc**
which includes its images from (src/docs/)**chapter/chap1/images** 
with **image:images/pic1.png**

this inluded in main.adoc would search for its image 
in **src/docs/images** 
instead **of src/docs/chapter/chap1/images**

another idea:

i recognised that at rendering time, mvn copies all resources to a temporary (resources folder?), where it then renders it. so i guess the problem is that, the images from the subchapters dont get copied to the temporary resources/src/docs/images folder, where it would be no problem to just use /images (instead of chapter/chap1/images)

**Comment by abelsromero** [comment]
> i recognised that at rendering time, mvn copies all resources to a temporary (resources folder?), where it then renders it. so i guess the problem is that, the images from the subchapters dont get copied to the temporary resources/src/docs/images folder, where it would be no problem to just use /images (instead of chapter/chap1/images)

Not really. Resources are copied directly from source to target and AsciiDoc sources are converted from source to target also, no temporal files are created (other than some managed by extensions like asciidoctor-diagram).

------

Thanks for the explanation, If I understand the example correctly, that behauviour is normal. And I realize can be confusing at first.
Btw, I am assuming not much experience with asciidoctor, apologies If I extend to long or sound pedantic. Just want to make sure to cover all.

To clarify:
1. Include works by copying the content and replacing the include::[] in the source file, and then converting.
Is not like converting the included source and embedding the result.
That means that when you have "chap1/chap1.adoc" included from "main.adoc", the converter just knows about "main.adoc" and the path where it resides. So, it's normal that if you have **(src/docs/)chapter/chap1/images** and use **image:images/pic1.png**, the converter expects to find the image in **(src/docs/)images/pic1.png**. 
Also, when the plugin copies the images into target, it assumes the path to the image to be relative to the sources root (**src/docs**), so it copies them to the target folder respecting the same structure, including the **chapter/chap1**. The conversion and the copying of resources are different actions.
2. Include and resources (images) paths are not relative to sources, but to the _baseDir_, which by default is the root of the sources. You can change that with the `baseDir` parameter, but the same path applies to all files. The other option for images is re-setting imagesdir as you already do, but you already saw that's not practical. Note _imagesdir_ will be appended to _baseDir_.
3. There's a special option `relativeBaseDir`, this is exclusive to the plugin (non-asciidoctor standard), that allows to make paths relative for each AsciiDoc source, but still the point 1 applies to includes. This is convenient in some cases, but is in fact anti-pattern.

Given the behauvior explained, the recomended way to manage images is to have them all under a common root independent from sources, they can share root of course (the "image catalog", see https://asciidoctor.org/docs/user-manual/#setting-the-location-of-images for more details). That way you only need to define imagesdir once and all documents can import them using the relative path from that root. No matter the relative path to the source file or if it a "includer", "included" or rendered on its own.


----

On other things you mentioned:



> on the level of docs there is a content adoc and a render adoc that includes the content adoc, so he content adoc does not need to know about all the adoc text formating headers.

You can also have the headers (I assume you mean attributes) in a different file and do something like show below instead of having multiple files. Think of includes as a way of composition, not of invocation.

```adoc
=My doc
ifdef::enable-X-options[]
include::_attributes.adoc[]
endif::enable-X-options[]
```

> also i just encountered that if i include an chpater, which changes the imagedir variable. And afterwards i want to show another image in the main adoc, then the imagedir is still set for the image folder path of the included documents images.

That's normal. Again, consider the included content as being copy-pasted, not invoked, so if an attribute is set, is set from that point on for the rest of the document.

Another thing is you can place sources that will ONLY be included in a folder with `_` prefix (eg. `_chapters`), that's considered *hidden* and won't be converted to the target, but you can still include them normally.

**Comment by smt-mj** [comment]
ok, so got everything correctly there.

yep i already have filename prefixe "_", that is excluded in the pom at the renderer.

also i have added a imagedirsave which gets set with the imagedir at the beginning of the "subchapter"-adocs and resets imagedir with its value back in the end of the document, so it dont "interferes" with the root documents imagedir structure after its included section in the root document.

thk for ur review 👍
