### ISSUE TITLE
Setting outputFile and outputDirectory

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#513]
Thank you for taking your time to talk with us!

**What is this issue about?**

- [x] Bug report
- [ ] Feature request
- [ ] Question

**Description**
When `outputFile` is set with an absolute path containing a file, and `outputDirectory` is set with a path that is not a subset of outputFile.
* Converted file is saved in `outputFile`, that's OK.
* However, `outputDirectory` path is also created empty.

**Comment by abelsromero** [comment]
Problem lies in `ensureOutputExists`, it should also check the content of `outputFile`.

**Comment by MSaguer** [comment]
Hi @abelsromero,

I've just had a quick look to this issue. 

A part of the problem lies in ensureOutputExists that should check the outputFile value before creating the folder. But that's no enough. 
If not created by the ensureOutputExists method, the output folder is also created by the filtering process that checks that outputDir exists and creates it if required (see DefaultMavenResourcesFiltering.filterResources()  l204). It is called by AsciiDoctorMojo.copyResources()

As filtering process should not be deactivated, a solution could be, when outputFile is an absolute path to change the outputDir as the outputFile parent directory.

Marc

**Comment by abelsromero** [comment]
> As filtering process should not be deactivated, a solution could be, when outputFile is an absolute path to change the outputDir as the outputFile parent directory.

I don't think we can do that. We should assume that if the user sets both properties, it is knowingly and with intent. For example the user may want to split html content and resources for different file content serving solutions.

Given what you found about `DefaultMavenResourcesFiltering.filterResources()` there's not much to do :man_shrugging: either close this or link it to https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/335.
