### ISSUE TITLE
Replace use of `baseDir` with `docdir` attribute

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#776]
Thank you for taking your time to talk with us!

**What is this issue about?**

- [ ] Bug report
- [x] Feature request
- [ ] Question

**Description**

`base_dir` option has some quirks and it would be recommended to use `docdir` attribute.
For context https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/Base.20directory.20and.20IDE

Tagging as 4.0.x since this is a breaking change involving rename of removal of current options `baseDir` and `relativeBaseDir'.

**Comment by mojavelinux** [comment]
I don't think that the base_dir option should be removed entirely. However, I could see a new option like setDocDir that sets the `docdir` attribute under the covers. The only time you need to set `docdir` is when the input is not a file, since the `docdir` is computed automatically if the input is a file.

There are cases when base_dir might still be used, but it should only be done by someone who very clearly understands why it is being used since it does have side effects. I'm not denying that there are flaws in the design, but I since we're not removing it from Asciidoctor itself yet, I wouldn't remove it outright from the Maven plugin. A strong warning would be appropriate though.

**Comment by abelsromero** [comment]
> The only time you need to set docdir is when the input is not a file, since the docdir is computed automatically if the input is a file.

That to me means we don't need to handle it. The maven plugin only deals with files.

**Comment by mojavelinux** [comment]
Great point.
